BlueBank/BlueBank/urls.py
from django.contrib import admin
from django.urls import path
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('index/', views.index2, name="index2"),
    path('criar/conta/', views.create_account, name="create_account"),


]

BlueBank/accounts/models.py
from django.db import models


# id é criado automaticamente

class Agency(models.Model):
    name_agency = models.CharField(max_length=128)
    agency_code = models.IntegerField(unique=True)

    def __str__(self):
        return self.name_agency


class Account(models.Model):
    CPF = models.CharField(max_length=128, unique=True)
    balance = models.FloatField(default=650)
    account_number = models.CharField(max_length=128, unique=True)
    agency = models.ForeignKey(Agency, on_delete=models.CASCADE, related_name="accounts")

    def transfer(self, account, value):

        if (self.balance - value < 0):
            raise ValueError(str(self.balance))

        account.credit(value)
        self.debit(value)

    def debit(self, value):
        self.balance = self.balance - value
        self.save()


    def credit(self, value):
        self.balance = self.balance + value
        self.save()

    @property
    def agency_code(self):
        return self.agency.agency_code

    def __str__(self):
        return self.CPF

BlueBank/accounts/forms.py
from django import forms
from localflavor.br.forms import BRCPFField

from accounts.models import Account, Agency


class TransferenciaForm(forms.Form):
    cpf1 = forms.CharField(required=True)
    account_number1 = forms.CharField(required=True)
    agency_code1 = forms.IntegerField(required=True)

    cpf2 = forms.CharField(required=True)
    account_number2 = forms.CharField(required=True)
    agency_code2 = forms.IntegerField(required=True)

    value = forms.FloatField(required=True)

    def is_valid(self):
        valid = True

        # Adiciona erros padrão, campo number com string ou algo do genero.

        if not super(TransferenciaForm, self).is_valid():
            self.adiciona_erro('Por favor, verifique os dados informados')
            valid = False

        # Verifica se existe conta com tais parametros.

        account1_exists = Account.objects.filter(CPF=self.cleaned_data['cpf1'],
                                                 account_number=self.cleaned_data['account_number1'],
                                                 agency__agency_code=self.cleaned_data['agency_code1']).exists()

        account2_exists = Account.objects.filter(CPF=self.cleaned_data['cpf2'],
                                                 account_number=self.cleaned_data['account_number2'],
                                                 agency__agency_code=self.cleaned_data['agency_code2']).exists()

        # Se não existir adiciona erro no formulario.

        if not account1_exists:
            self.adiciona_erro('Dados da conta de origem incorretos')

        if not account2_exists:
            self.adiciona_erro('Dados da conta de destino incorretos')

        # Se for a mesma conta
        if self.cleaned_data['account_number1'] == self.cleaned_data['account_number2'] or self.cleaned_data['cpf1'] == \
                self.cleaned_data['cpf2']:
            self.adiciona_erro("Existem dados repetidos nos formularios!")
            valid = False

        # Se valor é menor/igual que 0
        if self.cleaned_data['value'] <= 0:
            self.adiciona_erro("Impossivel transferir valores negativos ou nulos!")
            valid = False

        return valid

    def adiciona_erro(self, mensagem):
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        errors.append(mensagem)


class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ["CPF", "account_number", "agency"]

        labels = {
            'account_number': 'Numero da Conta',
            'agency': 'Agencia'
        }

        error_messages = {
            'CPF': {
                'unique': 'CPF já cadastrado',
            },
            'account_number': {
                'unique': 'Numero de conta já existe'
            }
        }

        agency = forms.ModelChoiceField(required=True, queryset=Agency.objects.all(), empty_label=None)
        cpf = forms.CharField(required=True, error_messages={'unique': 'message'})
        account_number = forms.CharField(required=True)

        # cpf = BRCPFField

        widgets = {
            'CPF': forms.TextInput(attrs={'class': "form-control", 'placeholder': 'xxx.xxx.xxx-xx'}),
            'account_number': forms.TextInput(attrs={'class': "form-control", 'placeholder': 'xxxxxxxx-x'}),
            'agency': forms.Select(attrs={'class': 'form-control'}),

        }

    def is_valid(self):

        valid = True

        if not super(AccountForm, self).is_valid():
            return False

        # Tentei usar BRCPFField mas nao consegui e fiz minha propria validação de cpf

        if not self.is_valid_cpf():
            self.adiciona_erro("CPF inválido")
            valid = False

        # Validar numero da conta

        if not self.is_valid_account_number():
            self.adiciona_erro("Numero de conta inválido")
            valid = False

        return valid

    def is_valid_cpf(self):
        cpf = self.cleaned_data['CPF']

        if len(cpf) != 14:
            return False

        if cpf[3] != '.' or cpf[7] != '.':
            return False

        if cpf[11] != '-':
            return False

        # Faço esses tratamentos pq pode ser que venha uma string em um local que eu não esteja monitorando

        for i in range(len(cpf)):
            try:
                int(cpf[i])
            except ValueError:
                if i != 3 and i != 7 and i != 11:
                    return False
        return True

    def is_valid_account_number(self):
        account_number = self.cleaned_data['account_number']

        if len(account_number) != 10:
            return False

        if account_number[8] != '-':
            return False

        # Faço esses tratamentos pq pode ser que venha uma string em um local que eu não esteja monitorando
        for i in range(len(account_number)):
            try:
                int(account_number[i])
            except ValueError:
                if i != 8:
                    return False

        return True

    def adiciona_erro(self, mensagem):
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        errors.append(mensagem)

BlueBank/accounts/views.py
from django.shortcuts import render, redirect

from django.contrib import messages

# Create your views here.
from accounts.forms import TransferenciaForm, AccountForm
from accounts.models import Account, Agency


def index(request):
    if request.method == 'POST':

        # Pega o formulario com os dados
        form_transferir = TransferenciaForm(request.POST)

        # Válida
        if form_transferir.is_valid():
            dados_form = form_transferir.cleaned_data

            try:
                make_transfer(request, dados_form)


                messages.success(request, "Transferencia concluida com sucesso!")

                return redirect('index')

            except ValueError as value:
                form_transferir.adiciona_erro(
                    "Você não tem %s em sua conta! (Seu saldo é %s)" % (str(dados_form['value']), str(value)))

        # Caso o formulario tenha erros ele manda com o erro
        return render(request, "index.html", {'form': form_transferir})

    # Metodo GET retorna o formulario limpo
    return render(request, "index.html")



def create_account(request):

    if request.method == 'POST':
        # Pega o formulario com os dados
        form_account = AccountForm(request.POST)

        # Válida
        if form_account.is_valid():

            # Pega os dados já validados

            dados_form = form_account.cleaned_data

            # Cria conta
            make_account(request, dados_form)

            messages.success(request, "Conta criada com sucesso!")

            return redirect('create_account')

        # Caso o formulario tenha erros ele manda com o erro
        return render(request, "create_account.html", {'form': form_account})

    # Metodo GET retorna o formulario limpo
    return render(request, "create_account.html", {'form': AccountForm()})


# Inicio da configuração da home alternativa

def index2(request):
    if request.method == 'POST':
        form_transferir = TransferenciaForm(request.POST)

        if form_transferir.is_valid():
            dados_form = form_transferir.cleaned_data

            try:
                make_transfer(request, dados_form)


                messages.success(request, "Transferencia concluida com sucesso!")

                return redirect('index2')

            except ValueError as value:
                form_transferir.adiciona_erro(
                    "Você não tem %s em sua conta! (Seu saldo é %s)" % (str(dados_form['value']), str(value)))


        return render(request, "index2.html", {'form': form_transferir})

    return render(request, "index2.html")




# Fim da configuração da home alternativa


def make_transfer(request, dados_form):

    # Pega as contas de acordo com os dados do formulario
    # Sem tratamento aqui porque o formulario já tem um "is.valid() -> dentro de forms.py"

    account1 = Account.objects.get(CPF=dados_form['cpf1'])
    account2 = Account.objects.get(CPF=dados_form['cpf2'])
    account1.transfer(account2, dados_form['value'])



def make_account(request, dados_form):

    # Cria uma conta nova

    Account.objects.create(CPF=dados_form['CPF'],
                           account_number=dados_form['account_number'],
                           agency=dados_form['agency'])

BlueBank/accounts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <title>Blue Bank</title>

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">


</head>

<body>

{% block body %}

{% endblock %}

</body>

</html>

BlueBank/accounts/templates/create_account.html
{% extends 'base.html' %}
{% block body %}

    <div class="col-md-4"></div>
    <div class="col-md-4" style="margin-top: 50px">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Criar conta</h3>
            </div>
            <div class="panel panel-body">
                <form class="form-horizontal" role="form"
                      action="{% url 'create_account' %}" method="post">
                    {% csrf_token %}

                    {{ form.as_p }}

                    {% if messages %}
                        <div class="alert-success-border">
                            {% for message in messages %}
                                <p style="color: white;"
                                   class="closebtn"
                                   onclick="this.parentElement.style.display='none';">&times;</p>
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>


                            {% endfor %}

                            <button type="button" class="close"
                                    data-dismiss="alert" aria-hidden="true">
                            </button>


                        </div>
                    {% endif %}

                    <button class="btn btn-primary btn-block" type="submit">Criar</button>

                    <ul class="btn btn-info btn-block" disabled>
                        <li>Sua conta vai ser criada com 650 de saldo!</li>
                    </ul>

                    <br>

                    <a href="{% url 'index' %}">Transferir dinheiro</a>

                </form>
            </div>

        </div>

    </div>

{% endblock %}

BlueBank/accounts/templates/index.html
{% extends 'base.html' %}
{% block body %}


    <h2>Blue Bank - Transferência</h2>
    <hr>

    <div class="col-md-2"></div>

    <form action="{% url 'index' %}" method="post" class="form-group-sm">
        {% csrf_token %}


        <div class="row">

            <div class="col-md-4">


                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Dados Conta Origem</h3>
                    </div>

                    <div class="panel panel-body">

                        <div class="form-group">
                            <input id="id_cpf1" name="cpf1" type="text" placeholder="CPF (xxx.xxx.xxx-xx)"
                                   class="form-control" required
                                   autofocus>
                        </div>

                        <div class="form-group">
                            <input id="id_agency_code1" name="agency_code1" type="number"
                                   placeholder="Número da agencia (xxxx) "
                                   class="form-control" required>
                        </div>

                        <div class="form-group">
                            <input id="id_account_number1" name="account_number1" type="text"
                                   placeholder="Número da conta (xxxxxxxx-x)" class="form-control"
                                   required>
                        </div>

                        <div class="form-group">
                            <input id="id_value" name="value" type="number"
                                   placeholder="Valor" class="form-control"
                                   required>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4">

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Dados Conta Destino</h3>
                    </div>

                    <div class="panel panel-body">

                        <div class="form-group">
                            <input id="id_cpf2" name="cpf2" type="text" placeholder="CPF (xxx.xxx.xxx-xx)"
                                   class="form-control"
                                   required
                                   autofocus>
                        </div>

                        <div class="form-group">
                            <input id="id_agency_code2" name="agency_code2" type="number"
                                   placeholder="Número da agencia (xxxx)"
                                   class="form-control" required>
                        </div>

                        <div class="form-group">
                            <input id="id_account_number2" name="account_number2" type="text"
                                   placeholder="Número da conta (xxxxxxxx-x)" class="form-control"
                                   required>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-3"></div>

        <div class="col-md-6">


            {% if form.errors %}
                <div class="alert alert-danger">
                    <button type="button" class="close"
                            data-dismiss="alert" aria-hidden="true">
                    </button>
                    <p style="color: indianred;"
                       class="closebtn"
                       onclick="this.parentElement.style.display='none';">&times;</p>
                    {{ form.non_field_errors }}

                </div>
            {% endif %}


            {% if messages %}
                <div class="alert-success">
                    {% for message in messages %}
                        <p style="color: indianred;"
                           class="closebtn"
                           onclick="this.parentElement.style.display='none';">&times;</p>
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>


                    {% endfor %}

                    <button type="button" class="close"
                            data-dismiss="alert" aria-hidden="true">
                    </button>


                </div>
            {% endif %}

            <button type="submit" class="btn btn-info btn-block">Transferir</button>


            <a class="btn btn-warning btn-block" href="{% url 'create_account' %}">Criar conta</a>

            <hr>


        </div>

    </form>

{% endblock %}

BlueBank/accounts/templates/index2.html
{% extends 'base.html' %}

{% block body %}

<div class="col-md-4"></div>

<div class="col-md-4">

    <h2>Blue Bank</h2>
    <hr>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Transferência</h3>
        </div>


        <div class="panel panel-body">
            <form action="{% url 'index2' %}" method="post" class="form-group-sm">
                {% csrf_token %}

                {% if form.errors %}
                    <div class="alert alert-danger">
                        <button type="button" class="close"
                                data-dismiss="alert" aria-hidden="true">
                        </button>
                        {{ form.non_field_errors }}
                    </div>
                {% endif %}

                {% if messages %}
                    <ul class="alert-success-border">
                        {% for message in messages %}
                            <li style="color: white; text-align: center" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}


                <h5 class="btn btn-info" disabled style="margin-block-end: 10px">Dados Conta Origem</h5>


                <div class="form-group">
                    <input id="id_cpf1" name="cpf1" type="text" placeholder="CPF (xxx.xxx.xxx-xx)" class="form-control"
                           required
                           autofocus>
                </div>

                <div class="form-group">
                    <input id="id_agency_code1" name="agency_code1" type="text" placeholder="Número da agencia (xxxx)"
                           class="form-control" required>
                </div>

                <div class="form-group">
                    <input id="id_account_number1" name="account_number1" type="text"
                           placeholder="Número da conta (xxxxxxxx-x)" class="form-control"
                           required>
                </div>

                <div class="form-group">
                    <input id="id_value" name="value" type="number"
                           placeholder="Valor" class="form-control"
                           required>
                </div>

                <hr/>

                <h5 class="btn btn-success" disabled style="margin-block-end: 10px">Dados Conta Destino</h5>

                <div class="form-group">
                    <input id="id_cpf2" name="cpf2" type="text" placeholder="CPF (xxx.xxx.xxx-xx)" class="form-control"
                           required
                           autofocus>
                </div>

                <div class="form-group">
                    <input id="id_agency_code2" name="agency_code2" type="text" placeholder="Número da agencia (xxxx)"
                           class="form-control" required>
                </div>

                <div class="form-group">
                    <input id="id_account_number2" name="account_number2" type="text"
                           placeholder="Número da conta (xxxxxxxx-x)" class="form-control"
                           required>
                </div>


                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Transferir</button>
                </div>


                <hr/>


                <a href="{% url 'create_account' %}">Criar conta</a>

            </form>
        </div>


    </div>


</div>

{% endblock %}